name: Update Translations
on:
  workflow_dispatch:
  schedule:
    # Daily at 3:00 a.m.
    - cron: '0 3 * * *'
jobs:
  update_translations:
    name: Update Translations
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing gettext
      run: sudo apt-get install gettext
    - name: Transifex integration
      run: |
        git config --global user.name "The Widelands Translations Bot"
        git config --global user.email "bunnybot@widelands.org"
        git fetch origin transifex
        git checkout master
        git merge --squash origin/transifex
    - name: Synchronizing translations
      run: |
        javac *.java
        ./buildcats.sh
    - name: Pushing changes
      run: |
        if [ ${{ github.event_name }} == "workflow_dispatch" ] || [ -n "$(git status -s i18n)" ]
        then
          git add .
          git commit -m "Automated translations update"
          git push origin master
        else
          git reset origin/master
          git checkout .
        fi
        git checkout transifex
        git merge -s recursive -Xtheirs master
        git push origin transifex
